import json
import logging
import os
import re
import fitz  # PyMuPDF
import pytesseract
from pdf2image import convert_from_bytes
from openai import OpenAI

logger = logging.getLogger(__name__)

class MedicalUnderwritingEngine:
    def __init__(self):
        logger.info("Initializing NLP Engine via OpenRouter API...")
        api_key = os.getenv("OPENROUTER_API_KEY")
        
        if not api_key or api_key.startswith("sk-or-v1-your-real"):
            logger.error("CRITICAL: OPENROUTER_API_KEY is missing or invalid.")
            self.client = None
        else:
            self.client = OpenAI(
                base_url="https://openrouter.ai/api/v1",
                api_key=api_key,
            )

    def extract_text(self, file_bytes: bytes) -> str:
        """Extracts text via PDF native text or Tesseract OCR fallback."""
        try:
            doc = fitz.open(stream=file_bytes, filetype="pdf")
            text = "\n".join([page.get_text() for page in doc]).strip()
            
            if len(text) < 50:
                logger.info("Scanned document detected. Engaging Tesseract OCR fallback...")
                images = convert_from_bytes(file_bytes)
                ocr_text = []
                for img in images:
                    ocr_text.append(pytesseract.image_to_string(img))
                text = "\n".join(ocr_text).strip()
                
            return text
        except Exception as e:
            logger.error(f"Document extraction failed: {e}")
            return ""

    def _clean_json_output(self, raw_output: str) -> dict:
        """Safely extracts JSON even if the LLM hallucinates markdown wrapping."""
        try:
            clean_str = re.sub(r'```json\n|```', '', raw_output).strip()
            return json.loads(clean_str)
        except json.JSONDecodeError:
            logger.error(f"JSON Parsing failed. Raw string: {raw_output}")
            return {"error": "Invalid JSON format generated by AI", "raw": raw_output}

    def analyze_clinical_risk(self, clinical_text: str) -> dict:
        """Passes text to OpenRouter and enforces the Red/Yellow/Green JSON schema."""
        if not self.client:
            return {"error": "OpenRouter client not initialized. Check API key."}
            
        if not clinical_text:
            return {"error": "No text extracted from document"}

        system_prompt = """You are a strict, highly accurate Medical Underwriter for an Indian Health Insurance provider. 
Analyze the clinical text and return ONLY a valid JSON object. Do not include any introductory or concluding remarks.

Risk Rating Rules:
- "RED": Severe, chronic, or critical illness (e.g., Cancer, Heart Failure, Stage 4 Kidney Disease, Unmanaged Diabetes with complications).
- "YELLOW": Managed lifestyle diseases requiring premium loading (e.g., controlled Type-2 Diabetes, Hypertension, Obesity, Asthma).
- "GREEN": Acute/curable issues with low recurrence (e.g., Dengue, Typhoid, Appendicitis, minor trauma, viral fever).

Output EXACTLY in this JSON schema:
{
    "patient_summary": "2-3 sentences summarizing the admission reason and discharge status.",
    "key_diagnoses": ["Condition 1", "Condition 2"],
    "risk_rating": "RED" | "YELLOW" | "GREEN",
    "underwriting_reason": "Justification for the risk rating based on the text."
}"""

        try:
            response = self.client.chat.completions.create(
                model="meta-llama/llama-3-8b-instruct", # You can swap this for any OpenRouter model string
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": f"Clinical Text:\n{clinical_text}"}
                ],
                temperature=0.0,
                extra_headers={
                    "HTTP-Referer": "http://localhost:8000", 
                    "X-Title": "MedSum-India POC"
                }
            )
            
            raw_output = response.choices[0].message.content
            return self._clean_json_output(raw_output)
            
        except Exception as e:
            logger.error(f"OpenRouter API error: {e}")
            return {"error": str(e)}